---
title: "Project_report"
author: "Conjugate Family"
date: "12/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
James <- readRDS("data/james.rds")
Durant <- readRDS("data/durant.rds")
Image <- readRDS("data/image.rds")
direct <- readRDS("data/direct.rds")
```

## Objective 

Nowadays, with AI technologies and big data being the main trend, using data analytical tools become widespread across industries. In this project, we aimed to utilize existing data to perform analysis on two NBA super stars, Lebron James and Kevin Durant through constructing data tables and visualizations using R. Although they are both considered as top basketball players, a lot of people tend to comment that they play with quite different styles. In fact, we thought this idea is worth exploring since both of them are capable of incredible basketball talent and strategies, thus learning from them will help other players to do better in the game as well. To further validate this opinion, we focused mostly on comparing and contrasting Lebron and KD’s performance during each game so that we would be able to conclude an overall trend through entire careers for both players.  In addition to that, we believed Shiny app is an excellent tool to present the result and allow us to filter out data with great efficiency because of its interactive feature. In the meantime, it will also be a convenient platform for people who have similar interest on investigating data of Lebron and KD.

## Data

The main sources of data in our project are two popular NBA stat websites: basketball-reference.com and espn.com.

In the data_scraping.R, firstly we scraped the Game Log of LeBron James (regular season, 2004-2019) and Kevin Durant (regular season, 2008-2019) from basketball-reference.com using `rvest`. Then we scraped both LeBron James's (2006-2018) and Kevin Durant's (2010-2014, 2016-2019) Playoffs Game Log. Next we get both players' shooting data during all the periods (regular season and Playoffs). At last we scraped their regular season average data from espn.com. We saved the raw data in james_raw.rds and durant_raw.rds.

In the data_cleaning.R, we firstly built some helper functions (in general: to.na, time.to.num; for "average": split1, split2; for "shooting": shooting.clean) to help cleaning the data. We cleaned the regular season data by modifying column names, removing redundant data, dealing with missing data and formatting, and then repeated a similar process for the playoff data. Next we formatted the regular season average data correctly and cleaned the shooting data with missing values and non-numerics. At last, we got two lists of well structured data: james.rds and durant.rds.

The variables codebook of our data is as the following:

Date -- Date of Game

Tm/Team -- Team Name

Home -- Whether Play at Home

Opp -- Opponent

GP -- Games Played

GS -- Games Started

MIN -- Minutes Per Game

MP -- Minutes Played

FG -- Field Goals

FGA -- Field Goal Attempts

FG% -- Field Goal Percentage

3P -- 3-Point Field Goals

3PA -- 3-Point Field Goal Attempts

3P% -- 3-Point Field Goal Percentage

FT -- Free Throws

FTA -- Free Throw Attempts

FT% -- Free Throw Percentage

ORB/OR -- Offensive Rebounds

DRB/DR -- Defensive Rebounds

TRB/REB -- Total Rebounds

AST -- Assists

STL -- Steals

BLK -- Blocks

TOV/TO -- Turnovers

PF -- Personal Fouls

PTS -- Points

GmSc -- Game Score

+/- -- Plus/Minus

Res.w -- Result of the game(Win/Lose)

Res.diff -- The difference of final scores

Split -- Splitting criterion

Value -- Categories used for separation

eFG% -- Effective field goal percent 

Ast'd -- Assist to turnover 

%Ast'd -- Assist to turnover percentage

## Method

Data table is a major tool for our data analysis. When doing the data cleaning part, we also added some summarizing statistics such as average, min and max etc. to get a general view of what the overall distribution look like. This step also made the latter plotting process much easier. Combined with tables, we also generated numerous plots using `ggplot` with our cleaned data. In fact, visualization helped us to detect the trend and difference with much less effort. What's more, We used the plots to find potential correlation of certain features used for performance evaluation, such as game location and field goals percentage. 

## Result

From the summary tables and plots, we first conducted data analysis on the ones that we thought were the most useful to determine their style. From that, we have the following ten findings: 

1. Through observing points vs. minutes scatterplots , we found that both Lebron and Durant generally played for more minutes in playoffs than regular seasons. This possibly due to NBA teams’ load management. This seems quite effective from our plot since compared to Durant, minutes per game for James during playoff season are stably higher than regular season without much fluctuation, while Durant’s minutes per game for playoff seasons vary a lot. This may explained the serious injury of Durant in this 2019-2020 season since he probably used too much energy during the regular seasons and failed to managed the time well. 

2. From the summary table and scatterplot of Assists vs. minutes, we realized that more assists occur later in playoffs than regular season. This makes sense since the duration of games during playoff are longer. In addition, compare to Durant, James has obviously more assists overall, which means he is more of an in-player and tends to create more space for his teammates. 

3. By observing rebounds and blocks from the summary table, we found that Lebron and KD achieve quite similar scores. 

4. We also found that there are more steals for James than Durant from the plot. This can indicate that Lebron has a more comprehensive sights when playing basketball. 

5. Observing the data of 3-pt shots,  Durant has slighter Higher one. Considering the fact that KD has the well-known long arms, physical difference could be reason to cause such difference. 

6. Durant has an obviously higher free throw than Lebron. This could be caused by similar reason above.

7. From the graph from advanced section, specifically the shot record by game location, we could see that there is no significant difference for home and road since NBA super star won’t be easily effected by environment. However, consistent with common sense, when they played at home, field goals percentage is higher overall. 

8. Through the plot of shot score by shot distance, compared to Durant, Lebron has a large preference of making shots at 3 to 10 feet while Durant’s goal percentage is more stable for various shot distance. Lebron tends to attack the rim, while Durant seems fine with whatever position.

9. From the plot of field goals attempts by shot type, we observed that Durant is huge fan of jump shot while for Lebron, although jump shot is the biggest proportion, it is relatively smaller than that of KD and more proportion of attempts fall in Lay-up. This again proves that KD tends to make the attempt at medium distance.

10. Lastly, the field goal percentages for both players are quite similar. The distributions are relatively flat for all time interval in the last quarter over years. KD might have slightly less fluctuation but the overall difference is trivial. These top NBA stars should have strong mindset so they won’t be affected too much by time. 

In conclusion, from the higher assists and steals amount, we can see that Lebron has a better understanding of the game and have more control over the court. He is the “good leader” type. In addition, he is more likely to play around the rim and make the attempt closer to nets. In contrast, Durant is the type of “good shooter,” since he has high free throw , larger field goals percentage of 3-pts and because of this, he has more flexibility over shot position. 

## Reference

We scraped the data from basketball-reference.com (https://www.basketball-reference.com/) and espn.com( https://www.espn.com). In addition, we learned to put animated ggplots into Shiny app via Gallery (https://shiny.rstudio.com/gallery/). 

Image urls are restored in image_saving.R